version: 2

models:
  - name: person
    description: 'A DBT MODEL FOR THE PERSONS IN THE RDS INSTANCE'
    columns:
      - name: person_id
        description: 'PERSON_ID OF THE PERSON'
        tests:
          - unique
          - not_null

  - name: customer
    description: 'A DBT MODEL FOR THE CUSTOMERS IN THE RDS INSTANCE, CUSTOMERS ARE PERSONS WHO HAVE MADE A PURCHASE'
    columns:
      - name: email
        description: 'EMAIL OF THE CUSTOMER'
        tests:
          - unique
          - not_null

  - name: prospect
    description: 'A DBT MODEL FOR THE PROSPECTSS IN THE RDS INSTANCE, PROSPECTS ARE PERSONS WHO WHAVENT MADE A PURCHASE YET'
    columns:
      - name: email
        description: 'EMAIL OF THE PROSPECT'
        tests:
          - unique
          - not_null
