version: 2

models:
  - name: person
    description: 'A DBT MODEL FOR THE PERSONS IN THE RDS INSTANCE'
    columns:
      - name: person_id
        description: 'PERSON_ID OF THE PERSON'
        tests:
          - unique
          - not_null
